/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package maconsoenergyuser;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.*;
import java.sql.ResultSet;
import java.util.HashMap;

/**
 *
 * @author you-users
 */
public class AppUser extends javax.swing.JFrame {
    
    private static String url  = "jdbc:mysql://127.0.0.1/maconsoenergy";
    private static String username  = "maconsoenergy_user1";
    private static String password  = "123456+azerty";
    private HashMap<String, Integer> typeConsoMap = new HashMap<>();
    private BDD maConsoEnergyBDD = new BDD();
    private InformationsClient info_client = new InformationsClient();
        
    
    /**
     * Creates new form AppUser
     */
    public AppUser() {
        initComponents();
        
        if (! maConsoEnergyBDD.Connexion(url, username, password)){
            System.exit(99);
            panel.setBackground(Color.RED);
        }
        else{
            panel.setBackground(Color.GREEN);
        }
    }
    
    private void initComboBoxTypeConso()
    {
        ResultSet resultSet;
        if (maConsoEnergyBDD.RequeteSQL("SELECT * FROM type_conso"))
        {
            resultSet = maConsoEnergyBDD.getResultSet();
            try { 
                while (resultSet.next()) {
                        // Recup toutes les données de la colonne Nom_Conso de la table type_conso
                        jComboBox2.addItem(resultSet.getString("Nom_Conso"));
                        
                        // Associe l'Item à la clé du type de conso
                        typeConsoMap.put(resultSet.getString("Nom_Conso"), resultSet.getInt("Id_Type_Conso"));
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connexion = new javax.swing.JPanel();
        valider_connexion = new javax.swing.JButton();
        login = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        liste_conso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        ajouter_liste = new javax.swing.JButton();
        color = new javax.swing.JPanel();
        déconnexion = new javax.swing.JButton();
        conso_bouton = new javax.swing.JButton();
        compte_bouton = new javax.swing.JButton();
        info_compte = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Adresse = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        code_postale = new javax.swing.JTextField();
        valider_info = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        ajout_conso = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        quantite = new javax.swing.JTextField();
        valider_conso = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 255));
        getContentPane().setLayout(new java.awt.CardLayout());

        connexion.setBackground(new java.awt.Color(61, 85, 134));

        valider_connexion.setText("Valider");
        valider_connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valider_connexionActionPerformed(evt);
            }
        });

        login.setText("Login");

        Password.setText("Mot de passe");
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("MA CONSO ENERGIE");

        panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout connexionLayout = new javax.swing.GroupLayout(connexion);
        connexion.setLayout(connexionLayout);
        connexionLayout.setHorizontalGroup(
            connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connexionLayout.createSequentialGroup()
                .addGroup(connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(connexionLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(connexionLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(connexionLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(valider_connexion))
                    .addGroup(connexionLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        connexionLayout.setVerticalGroup(
            connexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, connexionLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(valider_connexion)
                .addGap(59, 59, 59))
        );

        getContentPane().add(connexion, "Card_connexion");

        liste_conso.setBackground(new java.awt.Color(61, 85, 134));

        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Type");

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Quantité");

        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Date");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        ajouter_liste.setText("Ajouter");
        ajouter_liste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter_listeActionPerformed(evt);
            }
        });

        color.setBackground(new java.awt.Color(119, 181, 254));

        déconnexion.setText("D");
        déconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                déconnexionActionPerformed(evt);
            }
        });

        conso_bouton.setText("Conso");
        conso_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conso_boutonActionPerformed(evt);
            }
        });

        compte_bouton.setText("Compte");
        compte_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compte_boutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout colorLayout = new javax.swing.GroupLayout(color);
        color.setLayout(colorLayout);
        colorLayout.setHorizontalGroup(
            colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(compte_bouton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conso_bouton)
                .addGap(55, 55, 55)
                .addComponent(déconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        colorLayout.setVerticalGroup(
            colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compte_bouton)
                    .addComponent(conso_bouton)
                    .addComponent(déconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout liste_consoLayout = new javax.swing.GroupLayout(liste_conso);
        liste_conso.setLayout(liste_consoLayout);
        liste_consoLayout.setHorizontalGroup(
            liste_consoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liste_consoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(liste_consoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(liste_consoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ajouter_liste)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(liste_consoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addComponent(color, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        liste_consoLayout.setVerticalGroup(
            liste_consoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liste_consoLayout.createSequentialGroup()
                .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(liste_consoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(liste_consoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(ajouter_liste)
                .addGap(47, 47, 47))
        );

        getContentPane().add(liste_conso, "Card_liste_conso");

        info_compte.setBackground(new java.awt.Color(61, 85, 134));

        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Nom");

        nom.setText("Nom");
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Adresse");

        Adresse.setText("jTextField4");
        Adresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdresseActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Code Postale");

        code_postale.setText("jTextField5");

        valider_info.setText("Valider");
        valider_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valider_infoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(119, 181, 254));

        jButton7.setText("Compte");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Conso");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("D");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout info_compteLayout = new javax.swing.GroupLayout(info_compte);
        info_compte.setLayout(info_compteLayout);
        info_compteLayout.setHorizontalGroup(
            info_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, info_compteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(valider_info)
                .addGap(100, 100, 100))
            .addGroup(info_compteLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(info_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(code_postale, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        info_compteLayout.setVerticalGroup(
            info_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(info_compteLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(code_postale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(valider_info)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        getContentPane().add(info_compte, "Card_info_compte");

        ajout_conso.setBackground(new java.awt.Color(61, 85, 134));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        quantite.setText("Quantité");
        quantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantiteActionPerformed(evt);
            }
        });

        valider_conso.setText("Valider");
        valider_conso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valider_consoActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Type d'énergie");

        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("Quantité");

        jPanel1.setBackground(new java.awt.Color(119, 181, 254));

        jButton1.setText("Compte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("Conso");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("D");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ajout_consoLayout = new javax.swing.GroupLayout(ajout_conso);
        ajout_conso.setLayout(ajout_consoLayout);
        ajout_consoLayout.setHorizontalGroup(
            ajout_consoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ajout_consoLayout.createSequentialGroup()
                .addGroup(ajout_consoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajout_consoLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(ajout_consoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantite, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ajout_consoLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(valider_conso)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ajout_consoLayout.setVerticalGroup(
            ajout_consoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajout_consoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(quantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(valider_conso)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        getContentPane().add(ajout_conso, "Card_ajout_conso");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouter_listeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter_listeActionPerformed
        initComboBoxTypeConso();
        CardLayout layoutM = (java.awt.CardLayout)getContentPane().getLayout();
        
        layoutM.show(getContentPane(), "Card_ajout_conso");
    }//GEN-LAST:event_ajouter_listeActionPerformed

    private void conso_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conso_boutonActionPerformed
        CardLayout layoutM = (java.awt.CardLayout)getContentPane().getLayout();
        
        layoutM.show(getContentPane(), "Card_liste_conso");
    }//GEN-LAST:event_conso_boutonActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed

    }//GEN-LAST:event_nomActionPerformed

    private void quantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantiteActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    //Permet de connaitre la taille du ResultSet en déplacant le curseur et en le remettant a sa au debut pour eviter des problemes de traitemen
    private void valider_connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valider_connexionActionPerformed

        String SQLreq = "SELECT Id_Foyer FROM login WHERE login LIKE '%" + login.getText() + "%' AND password LIKE '%" + Password.getText() + "%';";
        
        if(maConsoEnergyBDD.RequeteSQL(SQLreq)){
            
            ResultSet resultat;
            
            resultat = maConsoEnergyBDD.getResultSet();
            int idFoyer=0;
            try{
                System.out.println(SQLreq);
                int longueur_table =0;
                while (resultat.next()){
                    idFoyer= resultat.getInt("Id_Foyer");
                    longueur_table= longueur_table+1;
                }
                
                if (longueur_table == 1){
                    CardLayout layoutM = (java.awt.CardLayout) getContentPane().getLayout();

                    info_client.LoginValide(idFoyer, maConsoEnergyBDD);
                    layoutM.show(getContentPane(), "Card_liste_conso");
                }
                else{
                    System.out.println("Le login ou le mot de passe ne sont pas corrects");
            }
            }catch (SQLException e) {
                e.printStackTrace();
            }
        } 

    }//GEN-LAST:event_valider_connexionActionPerformed

    private void compte_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compte_boutonActionPerformed
        CardLayout layoutM = (java.awt.CardLayout)getContentPane().getLayout();
        
        layoutM.show(getContentPane(), "Card_info_compte");
        String SQLreq = "SELECT * FROM foyer;";
        
        if(maConsoEnergyBDD.RequeteSQL(SQLreq)){
            
            ResultSet resultat;
            
            resultat = maConsoEnergyBDD.getResultSet();
                System.out.println(SQLreq);
                
                nom.setText(info_client.getNom());
                Adresse.setText(info_client.getAdresse());
                code_postale.setText(info_client.getCodePostale());
        } 
        
    }//GEN-LAST:event_compte_boutonActionPerformed

    private void valider_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valider_infoActionPerformed
        
        CardLayout layoutM = (java.awt.CardLayout)getContentPane().getLayout();
        
        // Récupere dans les champs du GUI les infos user
        String nom_n = nom.getText();
        String add_n = Adresse.getText();
        String cp_n = code_postale.getText();
        info_client.UpdateClassInfoClient(nom_n, add_n, cp_n);
        
        info_client.UpdateBDDInfoClient();
        
        layoutM.show(getContentPane(), "Card_liste_conso");
    }//GEN-LAST:event_valider_infoActionPerformed

    private void valider_consoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valider_consoActionPerformed
        
        int n_quantite = Integer.valueOf(quantite.getText());
        int n_id_type_conso = typeConsoMap.get(jComboBox2.getSelectedItem().toString());
        int n_id_foyer = info_client.getIdFoyer();
        
        info_client.InsertClassQuantiteCLient(n_quantite, n_id_type_conso, n_id_foyer);
        info_client.InsertQuantiteClient();
        
        CardLayout layoutM = (java.awt.CardLayout)getContentPane().getLayout();
        
        layoutM.show(getContentPane(), "Card_liste_conso");
    }//GEN-LAST:event_valider_consoActionPerformed

    private void déconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_déconnexionActionPerformed
        CardLayout layoutM = (java.awt.CardLayout)getContentPane().getLayout();
        
        layoutM.show(getContentPane(), "Card_connexion");
    }//GEN-LAST:event_déconnexionActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CardLayout layoutM = (java.awt.CardLayout)getContentPane().getLayout();
        
        layoutM.show(getContentPane(), "Card_liste_conso");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout layoutM = (java.awt.CardLayout)getContentPane().getLayout();
        
        layoutM.show(getContentPane(), "Card_info_compte");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        CardLayout layoutM = (java.awt.CardLayout)getContentPane().getLayout();
        
        layoutM.show(getContentPane(), "Card_liste_conso");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        CardLayout layoutM = (java.awt.CardLayout)getContentPane().getLayout();
        
        layoutM.show(getContentPane(), "Card_liste_conso");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        CardLayout layoutM = (java.awt.CardLayout)getContentPane().getLayout();
        
        layoutM.show(getContentPane(), "Card_connexion");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CardLayout layoutM = (java.awt.CardLayout)getContentPane().getLayout();
        
        layoutM.show(getContentPane(), "Card_connexion");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void AdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdresseActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adresse;
    private javax.swing.JTextField Password;
    private javax.swing.JPanel ajout_conso;
    private javax.swing.JButton ajouter_liste;
    private javax.swing.JTextField code_postale;
    private javax.swing.JPanel color;
    private javax.swing.JButton compte_bouton;
    private javax.swing.JPanel connexion;
    private javax.swing.JButton conso_bouton;
    private javax.swing.JButton déconnexion;
    private javax.swing.JPanel info_compte;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel liste_conso;
    private javax.swing.JTextField login;
    private javax.swing.JTextField nom;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField quantite;
    private javax.swing.JButton valider_connexion;
    private javax.swing.JButton valider_conso;
    private javax.swing.JButton valider_info;
    // End of variables declaration//GEN-END:variables
}
