/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package maconsoenergyuser;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.*;

/**
 *
 * @author r.topolovac
 */
public class AppUser extends javax.swing.JFrame {

    private static String url  = "jdbc:mysql://localhost/maconsoenergy";
    private static String username  = "maconsoenergy_user1";
    private static String password  = "123456+azerty";
    private BDD maConsoEnergyBDD = new BDD();
    
    /**
     * Creates new form AppUser
     */
    public AppUser() {
        initComponents();
        
        // Initilaistaion des composants de la GUI
        if (! maConsoEnergyBDD.Connexion(url, username, password))
            System.exit(99);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Conso = new javax.swing.JPanel();
        jButton_gotoprofile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Profile = new javax.swing.JPanel();
        jButton_gotoconso = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel_Conso.setBackground(new java.awt.Color(153, 255, 255));

        jButton_gotoprofile.setText("GO TO PROFIL");
        jButton_gotoprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gotoprofileActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("CONSOMMATION");

        javax.swing.GroupLayout jPanel_ConsoLayout = new javax.swing.GroupLayout(jPanel_Conso);
        jPanel_Conso.setLayout(jPanel_ConsoLayout);
        jPanel_ConsoLayout.setHorizontalGroup(
            jPanel_ConsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConsoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel_ConsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_gotoprofile)
                    .addComponent(jLabel2))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel_ConsoLayout.setVerticalGroup(
            jPanel_ConsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ConsoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(jButton_gotoprofile)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Conso, "CardConso");

        jPanel_Profile.setBackground(new java.awt.Color(255, 102, 102));

        jButton_gotoconso.setText("GO TO CONSO");
        jButton_gotoconso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gotoconsoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("PROFIL");

        javax.swing.GroupLayout jPanel_ProfileLayout = new javax.swing.GroupLayout(jPanel_Profile);
        jPanel_Profile.setLayout(jPanel_ProfileLayout);
        jPanel_ProfileLayout.setHorizontalGroup(
            jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProfileLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_gotoconso, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel_ProfileLayout.setVerticalGroup(
            jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProfileLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton_gotoconso)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Profile, "CardProfile");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_gotoprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gotoprofileActionPerformed
        // TODO add your handling code here:
        CardLayout layoutM = (java.awt.CardLayout)getContentPane().getLayout();
        
        layoutM.show(getContentPane(), "CardProfile");
        
    }//GEN-LAST:event_jButton_gotoprofileActionPerformed

    private void jButton_gotoconsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gotoconsoActionPerformed
        // TODO add your handling code here:
        CardLayout layoutM = (java.awt.CardLayout)getContentPane().getLayout();
        
        layoutM.show(getContentPane(), "CardConso");
    }//GEN-LAST:event_jButton_gotoconsoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_gotoconso;
    private javax.swing.JButton jButton_gotoprofile;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel_Conso;
    private javax.swing.JPanel jPanel_Profile;
    // End of variables declaration//GEN-END:variables
}
