/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package maconsoenergyuser;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author l.limousin
 */
public class GUI extends javax.swing.JFrame {

    private static String url  = "jdbc:mysql://localhost/maconsoenergy";
    private static String username  = "root";
    private static String password  = "";
    private BDD maConsoEnergyBDD = new BDD();
        
    private void initComboBoxTypeConso()
    {
        ResultSet resultSet;
        if (maConsoEnergyBDD.RequeteSQL("SELECT * FROM type_conso"))
        {
            resultSet = maConsoEnergyBDD.getResultSet();
            try { 
                while (resultSet.next()) {
                        // Recup toutes les données de la colonne Nom_Conso de la table type_conso
                        CBTypeConso.addItem(resultSet.getString("Nom_Conso"));
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    private void FonctionGetTF() 
    {
        String adresse = TFAdresse.getText();
        String nomprenom = TFNomPrenom.getText();
        String codepostal = TFCodePostal.getText();
        String quantite = TFQuantite.getText();


        String requete = "INSERT INTO foyer (Nom_Foyer, Adresse, code_postal) VALUES ('"+nomprenom+"','"+adresse+"','"+codepostal+"')";
        
        //maConsoEnergyBDD.UpdateSQL(requete);

        //maConsoEnergyBDD.getStatement().close();
        System.out.println("Données insérés dans la BDD "+"('"+nomprenom+"','"+adresse+"','"+codepostal+"')");
    }





    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        // Initilaistaion des composants de la GUI
        if (! maConsoEnergyBDD.Connexion(url, username, password))
            System.exit(99);
        
        initComboBoxTypeConso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BoutonValider = new javax.swing.JButton();
        TFAdresse = new javax.swing.JTextField();
        LabelFoyer = new javax.swing.JLabel();
        TFNomPrenom = new javax.swing.JTextField();
        TFCodePostal = new javax.swing.JTextField();
        LabelConsommation = new javax.swing.JLabel();
        TFQuantite = new javax.swing.JTextField();
        LabelEquivalence = new javax.swing.JLabel();
        LabelUnite = new javax.swing.JLabel();
        LabelAdresse = new javax.swing.JLabel();
        LabelNomPrenom = new javax.swing.JLabel();
        LabelCodePostal = new javax.swing.JLabel();
        LabelTypeConso = new javax.swing.JLabel();
        LabelQuantite = new javax.swing.JLabel();
        LabelUnite2 = new javax.swing.JLabel();
        LabelKWH = new javax.swing.JLabel();
        LabelKWH2 = new javax.swing.JLabel();
        CBTypeConso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BoutonValider.setText("Valider");
        BoutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonValiderActionPerformed(evt);
            }
        });

        TFAdresse.setToolTipText("");
        TFAdresse.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TFAdresse.setName(""); // NOI18N
        TFAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAdresseActionPerformed(evt);
            }
        });

        LabelFoyer.setText("Foyer");

        TFNomPrenom.setToolTipText("");
        TFNomPrenom.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TFNomPrenom.setName(""); // NOI18N
        TFNomPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNomPrenomActionPerformed(evt);
            }
        });

        TFCodePostal.setToolTipText("");
        TFCodePostal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TFCodePostal.setName(""); // NOI18N

        LabelConsommation.setText("Consommation");

        LabelEquivalence.setText("Equivalence :");

        LabelUnite.setText("Unité : ");

        LabelAdresse.setText("Adresse :");

        LabelNomPrenom.setText("Nom et Prénom :");

        LabelCodePostal.setText("Code Postal : ");

        LabelTypeConso.setText("Type de conso :");

        LabelQuantite.setText("Quantité :");

        LabelUnite2.setText("0");

        LabelKWH.setText("0");

        LabelKWH2.setText("KWH");

        CBTypeConso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTypeConsoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelQuantite)
                                    .addComponent(LabelEquivalence)
                                    .addComponent(LabelTypeConso))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BoutonValider)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(LabelKWH)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelKWH2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LabelUnite)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LabelUnite2))))
                                    .addComponent(TFNomPrenom)
                                    .addComponent(TFAdresse)
                                    .addComponent(CBTypeConso, 0, 195, Short.MAX_VALUE)
                                    .addComponent(TFCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LabelCodePostal)
                            .addComponent(LabelNomPrenom)
                            .addComponent(LabelAdresse)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(LabelConsommation))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(LabelFoyer)))
                .addGap(59, 59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelFoyer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAdresse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNomPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNomPrenom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCodePostal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelConsommation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTypeConso)
                    .addComponent(CBTypeConso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelUnite)
                    .addComponent(LabelQuantite)
                    .addComponent(LabelUnite2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEquivalence)
                    .addComponent(LabelKWH)
                    .addComponent(LabelKWH2))
                .addGap(18, 18, 18)
                .addComponent(BoutonValider)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonValiderActionPerformed
        // TODO add your handling code here:
        System.out.println("Bonjour");
        FonctionGetTF();
    }//GEN-LAST:event_BoutonValiderActionPerformed

    private void TFNomPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNomPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNomPrenomActionPerformed

    private void TFAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFAdresseActionPerformed

    private void CBTypeConsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTypeConsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBTypeConsoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
                
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonValider;
    private javax.swing.JComboBox<String> CBTypeConso;
    private javax.swing.JLabel LabelAdresse;
    private javax.swing.JLabel LabelCodePostal;
    private javax.swing.JLabel LabelConsommation;
    private javax.swing.JLabel LabelEquivalence;
    private javax.swing.JLabel LabelFoyer;
    private javax.swing.JLabel LabelKWH;
    private javax.swing.JLabel LabelKWH2;
    private javax.swing.JLabel LabelNomPrenom;
    private javax.swing.JLabel LabelQuantite;
    private javax.swing.JLabel LabelTypeConso;
    private javax.swing.JLabel LabelUnite;
    private javax.swing.JLabel LabelUnite2;
    private javax.swing.JTextField TFAdresse;
    private javax.swing.JTextField TFCodePostal;
    private javax.swing.JTextField TFNomPrenom;
    private javax.swing.JTextField TFQuantite;
    // End of variables declaration//GEN-END:variables
}
